version: '3'
services:
    python3:
        restart: always
        build: .
        container_name: 'python3'
        tty: true
        volumes:
            - ./src:/root/src
        working_dir: '/root/src'